SELECT *, [city_id]
      ,[city_name]
      ,[fecha_hora]
      ,[latitud]
      ,[longitud]
      ,[temperatura]
      ,[temperatura_min]
      ,[temperatura_max]
      ,[temperatura_sensacion]
      ,[nubosidad]
      ,[humedad]
      ,[viento_intensidad]
      ,[viento_sentido]
      ,[viento_intensidad_rafagas]
      ,[lluvia_1h]
      ,[ultimo]
      ,[clima_principal_es]
  FROM [ClimaTp].[dbo].[Clima]
