SELECT *,[ID]
      ,[Latitud]
      ,[Longitud]
      ,[Severidad]
      ,[TipoCorte]
      ,[Prestadora]
      ,[Partido]
      ,[Localidad]
      ,[Subestacion]
      ,[Alimentador]
      ,[UsuariosAfectados]
      ,[HoraEstimadaNormalizacion]
      ,[FechaInicio]
      ,[FechaFin]
      ,[FechaRegistro]
      ,[FechaActualizacion]
  FROM [CortesEnreTp].[dbo].[cortes_enre]
